config/routes.rb
Rails.application.routes.draw do
  root "blocks#index"

  resources :blogs, only: [:index, :show]
  resources :blocks, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    file, code = params[:block].split("__")

    spec_path = "spec/#{file}_spec.rb"

    if valid_file?(file)
      write_spec(spec_path, code)
      flash.now[:alert] = "Success check #{spec_path}"
    else
      flash.now[:alert] = "File not found"
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  def block_params
    params.require(:block)
  end

  private

  def valid_file?(path)
    unless path.nil?
      return File.file?('app/' + path + '.rb')
    end

    false
  end

  def write_spec(path, code)
    File.open(path, "w") { |f|
      f.write code
    }
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blocks/index.html.erb
<%= stylesheet_link_tag "style" %>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<p>
  To use:<br/>
  write the path to file relative to 'app/' without the .rb<br/>
</p>

<body mode="maker">
  <table>
    <td>
      <div class="blockly-editor">
        <%= form_with(url: blocks_path, method: :post, remote: true) do |form| %>
          <%= form.hidden_field(:block, id: 'block', value: "nil") %>
          <%= button_tag(type: 'submit', id: "done", class: "mode-edit mdl-button mdl-js-button") do %>
           Done
          <% end %>
        <% end %>
        <div id="blocklyDiv" style="height: 800px; width:1000px;">

        </div>
      </div>
    </td>
    <td>
      <div id='textarea' class='show-white-space'>
        Your code will appear here
      </div>
    </td>
  </table>


  <script src="https://unpkg.com/blockly"></script>

  <%= javascript_include_tag "banner_alert", defer: "defer" %>
  <%= javascript_include_tag "blocks/ruby", defer: "defer" %>
  <%= javascript_include_tag "generators/ruby_generator", defer: "defer" %>
  <%= javascript_include_tag "ruby_toolbox", defer: "defer" %>
</body>

app/views/blogs/index.html.erb
<%= stylesheet_link_tag "style" %>
<%= javascript_include_tag "banner_alert" %>
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>


<h1>blogs</h1>

<ul>
  <% @blogs.each do |blog| %>
    <li>
      <a href="/blogs/<%= blog.id %>">
        <%= blog.title %>
      </a>
    </li>
  <% end %>
</ul>
<p>
  To use:<br/>
  write the path to file relative to 'app/' without the .rb<br/>
</p>

<body mode="maker">
  <table>
    <td>
      <div class="blockly-editor">
        <button class="mode-maker mdl-button" hidden id="edit">Edit</button>

        <form action="/blocks" method="post" data-remote="true">
          <input id="block" name="block" value="nil" type="hidden"/>
          <button class="mode-edit mdl-button mdl-js-button" id="done" type="submit">Done</button>
        </form>

        <button class="mode-blockly mdl-button mdl-js-button" hidden id="save">Save</button>

        <div id="blocklyDiv" style="height: 800px; width:1000px;">

        </div>
      </div>
    </td>
    <td>
      <div id='textarea' class='show-white-space'>
        lol
      </div>
    </td>
  </table>


  <script src="https://unpkg.com/blockly"></script>

  <%= javascript_include_tag "blocks/ruby", defer: "defer" %>
  <%= javascript_include_tag "generators/ruby_generator", defer: "defer" %>
  <%= javascript_include_tag "ruby_toolbox", defer: "defer" %>
</body>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>

<p><%= @blog.body %></p>

<a href="<%= blogs_path %>">back</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>